### ISSUE TITLE
Wrong order in alarm register

### ISSUE THREAD

**Issue by deshipu** [adafruit/Adafruit_CircuitPython_DS3231#2]
I just fixed a bug in https://github.com/adafruit/Adafruit-uRTC/commit/286c65d4746a8cfc2a67430d2fdcdb5c0aa95d62 where I was using the wrong order of registers for the alarm setting. This should probably also fixed here.

**Comment by tannewt** [comment]
Thanks for the heads up! I redid the alarm stuff when I switched to the Register model. So, it shouldn't be an issue in this driver.
