### ISSUE TITLE
Error when importing:  line 97  _calibration unexpected keyword 'signed'

### ISSUE THREAD

**Issue by stlentz** [adafruit/Adafruit_CircuitPython_DS3231#28]
Module is not working on beagle board black.  Since the line reporting the error is a recent addition to the code, can you check that it is correct?  

debian@beaglebone:/var/lib/cloud9$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import busio
>>> import adafruit_ds3231
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ds3231.py", line 67, in <module>
    class DS3231:
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ds3231.py", line 97, in DS3231
    _calibration = i2c_bits.RWBits(8, 0x10, 0, 8, signed=True)
TypeError: __init__() got an unexpected keyword argument 'signed'

**Comment by ladyada** [comment]
make sure you have upgraded *all* pip packages

**Comment by stlentz** [comment]
OK, fixed.  Adafruit_ds3231.py was installed, but not Adafruit_ds3231.mpy.   Real PITA to move that file into the right place (/usr/local/bin/python3.7/dist-packages), the online guides are not really adequate, I used scp from my Mac.  Would be nice if PIP3 installed the files.

I do appreciate the support but I’m sort of worried how much longer people will bother with beagle board or will everyone just move to RPi. 

Anyway, thanks for the help.

-Steve

**Comment by ladyada** [comment]
you dont need or use the .mpy files on linux they are used for circuitpython boards only, something else was likely amiss with the install.
