### ISSUE TITLE
Time not advanceing

### ISSUE THREAD

**Issue by JustSumDad** [adafruit/Adafruit_CircuitPython_DS3231#31]
Sorry if this is the wrong place to submit this issue but here goes 

Installed DS3231 on Rpi4 as per instructions using latest raspian lite build booting off USB SSD
at first I thought it was working as with no internet access the date command reported the correct date when a cold start was done
then after an over night cold test, I discovered the date/time raspian was reporting was actually the time it was shut down.
Not the current time, it seems the DS3231 is saving the time to the chip and the system is pulling it back but its not running when the PI is cold.
This could easily be something I have missed, I am not great at this  :)
This is my exact order of installation.
#1) sudo apt-get update && sudo apt-get upgrade
#2) sudo apt install python3-pip
#3) sudo pip3 install adafruit-circuitpython-lis3dh
#4) sudo pip3 install adafruit-circuitpython-ds3231

Thanx

**Comment by ladyada** [comment]
what is the exact url of the DS3231 you purchased?

**Comment by JustSumDad** [comment]
Thank you for your time Ladyada.  I got them from amazon.

https://www.amazon.ca/DS3231-Precision-Module-Arduino-Raspberry/dp/B07GRRBB8B/ref=sr_1_1_sspa?dchild=1&keywords=ds3231&qid=1603036054&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyNlBaSkFINVJWVlZEJmVuY3J5cHRlZElkPUEwMzEyMjczRE1USjFJQUZWRTdSJmVuY3J5cHRlZEFkSWQ9QTA5Njc1NzUyOVBVTk1GRlNIT0NQJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

**Comment by ladyada** [comment]
kk please contact the vendor for tech support - its likely not a software issue!

**Comment by JustSumDad** [comment]
Thank you for verifying I am doing it correctly, I was starting to think maybe the way the driver was I had to make a different call to get the time/date from the chip to the O/S

Thank you again!
