### ISSUE TITLE
Ability to check button battery voltage?

### ISSUE THREAD

**Issue by RagingRoosevelt** [adafruit/Adafruit_CircuitPython_DS3231#41]
Is there any way to check the button battery voltage?  I know the python interface implemented in this module doesn't have a property for that, but does the hardware itself expose battery voltage on a register?  I tried looking in the datasheets but I'm not quite sure I fully grokked what I was reading.

**Comment by ladyada** [comment]
nope, it is not exposed as an analog reading!
