### ISSUE TITLE
Date is showing day/month instead of month/day

### ISSUE THREAD

**Issue by oldblackcrow** [adafruit/Adafruit_CircuitPython_DS3231#43]
Hello. Just ran the code as it is on your page and the date displays as:

Sunday 20/5/2022

Is there a way to make it 05/20/2022?

Thanks!

**Comment by tannewt** [comment]
This isn't really an issue with the library. Please ask on the [Adafruit forum](https://forums.adafruit.com/viewforum.php?f=60) or [Discord](https://adafru.it/discord) next time.

However, you want:

```python
    print(
        "The date is {} {}/{}/{}".format(
            days[int(t.tm_wday)], t.tm_mon, t.tm_mday, t.tm_year
        )
    )
```
