### ISSUE TITLE
Is there a way to use this library with micropython ESP32?

### ISSUE THREAD

**Issue by Denizik12** [adafruit/Adafruit_CircuitPython_DS3231#45]
I have downloaded the library included all the libraries that were needed, but stil it won't work. Now I get this error message that I can't fix. " ImportError: no module named 'pkg_resources' ". The reason I get this error is because the library isn't made for ESP32. In the board.py library I don't see the ESP32 in the list that is why I get that error message. Is there a way to make it work with a ESP32.

**Comment by tannewt** [comment]
Generally Blinka is used to run CircuitPython libraries on MicroPython. There is a related guide for [using Blinka in MP on the Pico](https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico).

CircuitPython now supports the ESP32 in 8.0.0 beta too. You could try that as well.

**Comment by FoamyGuy** [comment]
closing this, comment above answers original question.
