### ISSUE TITLE
Are there instructions for using this with the Raspberry Pi Pico controller

### ISSUE THREAD

**Issue by hairem** [adafruit/Adafruit_CircuitPython_DS3231#46]
I am trying to use this library to run my ds3231 on my raspberry pi pico but the instructions and examples are for if I was using a regular pi board. I have multiple I2C and URAT already set up and I am unsure how to use this library with those micro-python settings for the pico. I have it wired into my project and can detect the address when I do an I2C scan, just need to know how to initialize the I2C for the pico instead of the PI.

**Comment by jposada202020** [comment]
hello hairem, normally this is for library issues, so you might not get the help or rapid answer that you expect
maybe you could try the https://adafru.it/discordchannels people could help you with that.  In the meantime maybe you could take a look here.
https://learn.adafruit.com/adafruit-ds3231-precision-rtc-breakout/circuitpython
or ask in the https://forums.adafruit.com/ Forums.

Thanks

**Comment by hairem** [comment]
I figured it would be something like that but I didn't see much other for
options to ask.

**Comment by jposada202020** [comment]
No worries, Adafruit Discord is a great place to find help in your projects. either the #help-with-projects or help-with-circuitpython channel. Good Luck :)
